<?php

if (! function_exists('csp_nonce')) {
    /**
     * csp_nonce() — Defense in Depth: Network/Edge Layer
     *
     * Returns the cryptographically random per-request nonce that was
     * generated by SecurityHeaders middleware. This nonce is embedded in
     * the Content-Security-Policy header as 'nonce-{value}' in the
     * script-src directive, and must be added to every legitimate inline
     * <script> tag in Blade templates:
     *
     *   <script nonce="{{ csp_nonce() }}">
     *       // your inline JS here
     *   </script>
     *
     * Any inline script WITHOUT this nonce attribute is blocked by the
     * browser's CSP engine — this mitigates XSS even if an attacker
     * successfully injects a <script> tag into the page HTML.
     *
     * Returns an empty string in the (impossible) case where the
     * middleware has not run, to prevent template errors.
     */
    function csp_nonce(): string
    {
        return app()->bound('csp-nonce') ? (string) app('csp-nonce') : '';
    }
}
